codecov:
    branch: master
    notify:
        require_ci_to_pass: yes

coverage:
    precision: 2
    round: down
    range: "70...100"

    status:
        project:
            default:
                enabled: yes
                target: 85%
                threshold: 5%


        patch:
            default:
                enabled: yes
                target: 85%

ignore:
    - "tests"
    - "*__init__.py"

comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false  # if true: only post the comment if coverage changes
    require_base: no        # [yes :: must have a base report to post]
    require_head: yes       # [yes :: must have a head report to post]
    branches: null          # branch names that can post comment
    after_n_builds: <number> #e.g., 5. The number of uploaded reports codecov will receive before posting a comment on a pull request.
