# This is a sample .typo-ci.yml file, it's used to configure how Typo CI will behave.
# Add it to the root of your project and push it to github.
---

# What language dictionaries should it use? Currently Typo CI supports:
# de
# en
# en_GB
# en_CA
# en_AU
# en_ZA
# es
# fr
# is
# it
# sw
dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - ".*"
  - "docs*"
  - "environment.yml"
  - "tools*"

# Any typos we should ignore?
excluded_words:
  - typoci
  # python packages -----------------------------
  - numpy
  - scipy
  - pytest
  - matplotlib
  # matplotlib ----------------------------------
  - pyplot
  - gca
  - plt
  # flake8 --------------------------------------
  - noqa
  # numpy ---------------------------------------
  - linalg
  - ndim
  - dtype
  - isclose
  - ndarray
  - hstack
  - matmul
  - arange
  - det
  - vstack
  # jupyter notebooks ---------------------------
  - jupyter
  - nbformat
  # iPython -------------------------------------
  - ipynb
  - ipywidgets
  - ipython
  # other ---------------------------------------
