name: test-environment
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.17
  - pandas=0.25
  - scipy=1.3.2
  - xarray>=0.12.3
  # - bottleneck>=1.1
  # - jsonschema=2.6
  - asdf=2.3
  # - deepdish=0.3.4
  # - cx_oracle
  # - oracle-instantclient
  # - libaio
  - flake8
  - pytest
  - pytest-cov
  - codecov
  - pydocstyle
  - sphinx
  - recommonmark
  - matplotlib
  - seaborn # only needed for xarray tutorial
  - openpyxl # only needed for pandas tutorial