name: test-environment
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.18
  - pandas=0.25
  - scipy=1.3
  - xarray=0.14
  - bottleneck=1.3
  - pint=0.10
  - asdf=2.5.1
  - flake8
  - pytest
  - pytest-cov
  - codecov
  - pydocstyle
  - sphinx
  - recommonmark
  - matplotlib
  - seaborn # only needed for xarray tutorial
  - openpyxl # only needed for pandas tutorial